### ISSUE TITLE
"This will not work with testrpc"

### ISSUE THREAD

**Issue by mcdee** [sogoiii/ecrecover-example#1]
Could you provide details as to why this will not work with testrpc?  I'm having trouble using a private chain (truffle doesn't want to deploy to it) so if I know the issues with testrpc I might be able to find some way to work around them.  Thanks!

**Comment by sogoiii** [comment]
my best guess is that it doesnt have the RPC mock for personal_sign, and personal_ecrecover? It could be that testrpc is still on web3 0.16.0 which was release in march 2016, and the updates to the evm happened in October 2016? 

Here are some references:
Here is the pull request in [go-ethereum](https://github.com/ethereum/go-ethereum/pull/2940)
An issue about the change: [go-ethereum](https://github.com/ethereum/go-ethereum/issues/3621)

**Comment by tkayyyyys** [comment]
Thanks for the helpful code @sogoiii !

Could you tell me which elements will not work on TESTRPC? The calls to web3.js or the ecrecover on the solidity side? Thinking about how I can unit test this..

Thanks!

**Comment by sogoiii** [comment]
@tkayyyyys it should all be working with ganache now.

**Comment by wimdetr** [comment]
@sogoiii I ran this program with ganache, and I get returned the 0x0 address; I obviously haven't changed any code. So it seems like there still is an issue? Help is much appreciated! :-)

**Comment by sogoiii** [comment]
@wimdetr I merged in your [pull request](https://github.com/sogoiii/ecrecover-example/pull/4). I also tested this against ganache-core version 2.1.0
